ITEM.name = "Papieros"
ITEM.description = "Przedmiot kosmetyczny, postać trzyma odpalonego papierosa między ustami.."
ITEM.category = "Outfit"
ITEM.model = "models/unconid/props_pack/cigarette.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "papieros"
ITEM.pacData = {

    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                            [1] = {
                                ["children"] = {
                                },
                                ["self"] = {
                                    ["Follow"] = true,
                                    ["UniqueID"] = "49e81ab55edf0d3b903c06798f0acded9f02994d827d81f604e45364c5ad5f4a",
                                    ["PointDUID"] = "",
                                    ["EditorExpand"] = false,
                                    ["PointCUID"] = "",
                                    ["AimPartName"] = "",
                                    ["NoTextureFiltering"] = false,
                                    ["Bone"] = "head",
                                    ["BlendMode"] = "",
                                    ["DrawOrder"] = 0,
                                    ["PositionOffset"] = Vector(-0.10000000149012, 0, 0),
                                    ["PointAUID"] = "",
                                    ["Position"] = Vector(0.070068359375, -9.3154296875, -3.9139404296875),
                                    ["AimPartUID"] = "",
                                    ["PointBUID"] = "",
                                    ["Hide"] = false,
                                    ["Name"] = "",
                                    ["AngleOffset"] = Angle(0, 0, 0),
                                    ["Angles"] = Angle(0, 0, 0),
                                    ["ClassName"] = "effect",
                                    ["Effect"] = "barrel_smoke_trailb",
                                    ["Rate"] = 1.77,
                                    ["Loop"] = true,
                                    ["IgnoreZ"] = false,
                                    ["EyeAngles"] = false,
                                    ["UseParticleTracer"] = false,
                                },
                            },
                        },
                        ["self"] = {
                            ["Skin"] = 0,
                            ["UniqueID"] = "a66b912e94983d5d4dac02b940f1ad8ab87a013aabdaf4fdcf5f283ff0f32627",
                            ["NoLighting"] = false,
                            ["AimPartName"] = "",
                            ["IgnoreZ"] = false,
                            ["AimPartUID"] = "",
                            ["Materials"] = "",
                            ["Name"] = "smokepoint",
                            ["LevelOfDetail"] = 0,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["Color"] = Vector(1, 1, 1),
                            ["Translucent"] = false,
                            ["DrawOrder"] = 0,
                            ["Alpha"] = 1,
                            ["Material"] = "",
                            ["Invert"] = false,
                            ["Bone"] = "head",
                            ["ModelModifiers"] = "",
                            ["BlendMode"] = "one;zero;one;zero",
                            ["BoneMerge"] = false,
                            ["Model"] = "models/pac/default.mdl",
                            ["Position"] = Vector(0.000244140625, 0, -2.07666015625),
                            ["Brightness"] = 1,
                            ["LegacyTransform"] = false,
                            ["Hide"] = false,
                            ["NoCulling"] = false,
                            ["Scale"] = Vector(1, 1, 1),
                            ["ClassName"] = "model2",
                            ["EditorExpand"] = true,
                            ["Size"] = -0.025,
                            ["EyeAngles"] = false,
                            ["NoTextureFiltering"] = false,
                            ["ForceObjUrl"] = false,
                            ["EyeTargetUID"] = "",
                            ["Angles"] = Angle(0, 0, 0),
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 2,
                    ["UniqueID"] = "76ada4e0e58ffe1033cebc8f023ffb26f3c5ba39ed5467d8455ecb7d6affd8f8",
                    ["NoLighting"] = false,
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Materials"] = "",
                    ["Name"] = "",
                    ["LevelOfDetail"] = 0,
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["Color"] = Vector(1, 1, 1),
                    ["Translucent"] = false,
                    ["DrawOrder"] = 0,
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["Invert"] = false,
                    ["Bone"] = "head",
                    ["ModelModifiers"] = "skin=2;",
                    ["BlendMode"] = "",
                    ["BoneMerge"] = false,
                    ["Model"] = "models/unconid/props_pack/cigarette.mdl",
                    ["Position"] = Vector(1.0404663085938, -8.0036010742188, -0.484375),
                    ["Brightness"] = 1,
                    ["LegacyTransform"] = false,
                    ["Hide"] = false,
                    ["NoCulling"] = false,
                    ["Scale"] = Vector(1, 1, 1),
                    ["ClassName"] = "model2",
                    ["EditorExpand"] = true,
                    ["Size"] = 1,
                    ["EyeAngles"] = false,
                    ["NoTextureFiltering"] = false,
                    ["ForceObjUrl"] = false,
                    ["EyeTargetUID"] = "",
                    ["Angles"] = Angle(-0.096074424684048, -1.4217040538788, -82.841400146484),
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["EditorExpand"] = true,
            ["OwnerName"] = "self",
            ["Name"] = "Papieros`",
            ["ClassName"] = "group",
            ["Hide"] = false,
            ["Duplicate"] = false,
            ["UniqueID"] = "ffdca3d4e834ce2a1265994f421f704dc0ee80c3cc3990f278b43473c0dc9c64",
        },
    },
    


}

